labels = {
    "MAIN_EFFECT": "SHAP Main Effect Value for\n%s",
    "INTERACTION_VALUE": "SHAP Interaction Value",
    "INTERACTION_EFFECT": "SHAP Interaction Value for\n%s and %s",
    "VALUE": "SHAP Value (Impact on Model Output)",
    "GLOBAL_VALUE": "Mean(|SHAP Value|) (Average Impact on Model Output Magnitude)",
    "VALUE_FOR": "SHAP Value for\n%s",
    "PLOT_FOR": "SHAP Plot for %s",
    "FEATURE": "Feature %s",
    "FEATURE_VALUE": "Feature Value",
    "FEATURE_VALUE_LOW": "Low",
    "FEATURE_VALUE_HIGH": "High",
    "JOINT_VALUE": "Joint SHAP Value",
    "MODEL_OUTPUT": "Model Output Value",
}
